version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - JWT_SECRET=your_jwt_secret
      - DB_URI=mongodb://mongo:27017/task-manager
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WINDOW_MS=900000  
      - RATE_LIMITER_MAX=100
      - RATE_LIMITER_MESSAGE='Too many requests, please try again later.'
    depends_on:
      - mongo
      - redis
    networks:
      - task_management

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - task_management
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - task_management

volumes:
  mongo_data:

networks:
  task_management:
